### ISSUE TITLE
When I launch another game and come back, the save is still gone.

### ISSUE THREAD

**Issue by ccs21** [WonderfulToolchain/ws-cartfriend#1]
Please watch my video

https://youtu.be/tLruFUQuHE8

what am i doing wrong?
  
When I launch another game and come back, the save is still gone.

**Comment by asiekierka** [comment]
There's an occasional corruption bug on SRAM->Flash writes which I haven't caught in initial testing.

**Comment by asiekierka** [comment]
Fixed as of CartFriend 0.1 beta 4.

**Comment by ccs21** [comment]
Works fine! thank you!
