### ISSUE TITLE
Import a save from old Flash Masta menu/tool?

### ISSUE THREAD

**Issue by TimeWarpGamer** [WonderfulToolchain/ws-cartfriend#15]
First off, thank you so much for this awesome tool for one of my most beloved handhelds.  Now onto my question--not sure if it's an issue, something I don't understand or an enhancement...

I have a few backed up saves (i.e. Klonoa and Judgment Silversword) that I made back when I was using the OLD (https://www.flashmasta.com/wp-content/uploads/2011/06/WS-Flash-Masta-Menu-8-29-16.zip) menu tool, and backed them up via the Flash Masta software tool on Mac (https://www.flashmasta.com/files/FlashMasta_Mac_1-21-16.dmg).  Is there a way to import these saves with your awesome launcher?  I tried restoring them via the Flash Masta software, but it didn't seem to work.  Thanks in advance for your time.

**Comment by asiekierka** [comment]
It should be sufficient to start the game with the new menu, *then* - after the destination game has been started at least once, and while no other game has been launched - restore the save file the traditional way.

Or is that not working?

**Comment by TimeWarpGamer** [comment]
Thanks so much for the quick reply.

Worked like a champ!  I loaded Klona once, powered off, transferred the save, and when I booted it up again it didn't go through the "backing up SRAM" process, game launched and my old save was there.  Thank you!

On a related note, I have other games saving SRAM scores/progress/etc. just fine, but every time I launch the game it goes through the "backing up SRAM" step.  Not much of a delay, given how superior your launcher is to the old one I used, but just curious if this repetitive step on launch is normal or if there's a way to turn it off.

**Comment by asiekierka** [comment]
Every time you switch between two games, it has to back up the first game's SRAM to Flash, then restore the second game's save backup to SRAM. This is normal, and a consequence of supporting per-slot save data on this specific hardware.
